### PR TITLE
Check scmReference and aqaReference

### LINKED ISSUE #498: Add check of release tags during pipeline and abort if incorrect
For release: the pipeline should include a check that ensures the `scmReference`  are correct set in the `testenv.properties` in aqa-tests repo and abort pipeline if they're not. 

example PR for updating aqa-tests release branch in  2022 Oct release https://github.com/adoptium/aqa-tests/pull/4065

This mitigates human error as the `scmReference` aren't known until the release and this needs to be manually input.

### PR DESCRIPTION
**Pull request by sophia-guo**
Drop the build if the scmReference is different from the the jdk branch information is aqa-tests release branch

Fix #498 

Signed-off-by: Sophia Guo <sophia.gwf@gmail.com>

### CODE REVIEW

File: pipelines/build/openjdk_pipeline.groovy [hunk 1]
```diff
@@ -27,6 +27,34 @@ node('worker') {
     // Fail if unable to clean..
     cleanWs notFailBuild: false
 
+    if (params.releaseType == 'Release' && params.aqaReference != '' && params.scmReference != '') {
+        def propertyFile = 'testenv.properties'
+        if (params.jdkVersion =='8' && params.targetConfigurations.contains('arm32Linux')) {
```
Comment (karianna) [inline pipelines/build/openjdk_pipeline.groovy:32]:
```suggestion
        if (params.jdkVersion == '8' && params.targetConfigurations.contains('arm32Linux')) {
```

File: pipelines/build/openjdk_pipeline.groovy [hunk 2]
```diff
@@ -27,6 +27,34 @@ node('worker') {
...
+            propertyFile = 'testenv_arm32.properties'
+        }
+        sh("curl -Os https://raw.githubusercontent.com/adoptium/aqa-tests/${params.aqaReference}/testenv/${propertyFile}")
+
+        def buildTag = ''
+        if (params.scmReference.contains('_adopt')) {
+            buildTag = params.scmReference.substring(0, params.scmReference.length() - 6) // remove appendix _adopt
```
Comment (karianna) [inline pipelines/build/openjdk_pipeline.groovy:39]:
```suggestion
            buildTag = params.scmReference.substring(0, params.scmReference.length() - 6) // remove _adopt suffix
```

File: pipelines/build/openjdk_pipeline.groovy [hunk 3]
```diff
@@ -27,6 +27,34 @@ node('worker') {
...
+                def branch = branchInfo[1]
+                if (branch != buildTag) {
+                    println "Warning: scmReference is ${buildTag}, which is different from ${item} in aqa-tests release branch . Please update aqa-tests release branch!"
+                    currentBuild.result = 'FAILURE'
+                    return
+                }
+                break
+            }
+        }
+    }
```
Comment (karianna) [inline pipelines/build/openjdk_pipeline.groovy:57]:
```suggestion
    }

```

**Review by karianna — APPROVED** [review]
LGTM

**Review by gdams — APPROVED** [review]
